--CREATE DATABASE [University]

CREATE TABLE Majors
(
	MajorID INT IDENTITY(1,1) PRIMARY KEY,
	Name NVARCHAR(50) NOT NULL
)

CREATE TABLE Students
(
	StudentID INT IDENTITY(1,1) PRIMARY KEY,
	StudentNumber INT NOT NULL,
	StudentName NVARCHAR(50) NOT NULL,
	MajorID INT FOREIGN KEY REFERENCES Majors(MajorID)
)

CREATE TABLE Payments
(
	PaymentID INT IDENTITY(1,1) PRIMARY KEY,
	PaymentDate DATE,
	PaymentAmmount DECIMAL(6,2),
	StudentID INT FOREIGN KEY REFERENCES Students(StudentID)
)

CREATE TABLE Subjects
(
	SubjectID INT IDENTITY(1,1) PRIMARY KEY,
	SubjectName NVARCHAR(50) NOT NULL,
)

CREATE TABLE Agenda
(
	StudentID INT FOREIGN KEY REFERENCES Students(StudentID),
	SubjectID INT FOREIGN KEY REFERENCES Subjects(SubjectID)
	PRIMARY KEY(StudentID, SubjectID)
)